[package]
name = "fontconfig-sys"
version = "0.1.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]
license = "MIT"

build = "build.rs"


[build-dependencies]
pkg-config = "0.3"

[dependencies]
libc = "0.2"

